language: node_js

node_js:
  - '10'

branches:
  only:
    - master

cache:
  yarn: true

after_success:
  - yarn test --coverage --coverageReporters=text-lcov | yarn run coveralls

before_deploy:
  - yarn build

deploy:
  provider: script
  script: yarn publish
  on:
    tags: true
